"""Created users table and added reference to incidents table

Revision ID: 49603aad040f
Revises: 8ba4934fdaa2
Create Date: 2026-09-16 14:44:00.779665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49603aad040f'
down_revision: Union[str, Sequence[str], None] = '8ba4934fdaa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('user_email', sa.String(), nullable=False),
        sa.Column('user_password', sa.String(), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True),    server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('user_id'),
        sa.UniqueConstraint('user_email')
    )
    op.add_column(
        'incidents',
        sa.Column('reported_by', sa.Integer(), nullable=False),
    )
    op.create_foreign_key(
        'incidents_reported_by_fkey',
        'incidents',
        'users',
        ['reported_by'],
        ['user_id'],
        ondelete='CASCADE',
    )

def downgrade() -> None:
    """Downgrade schema."""
    op.execute(
        "ALTER TABLE incidents DROP CONSTRAINT IF EXISTS "
        "incidents_reported_by_fkey"
    )
    op.execute("ALTER TABLE incidents DROP COLUMN IF EXISTS reported_by")
    op.drop_table("users")
